import { Card, CardBody } from "@heroui/card";
import { Chip } from "@heroui/chip";
import { DollarSign, TrendingUp, Users, Zap } from "lucide-react";

interface ReferralStats {
  totalReferrals: number;
  tier1Referrals: number;
  tier2Referrals: number;
  totalVolume: number;
  tier1Volume: number;
  tier2Volume: number;
  totalEarnings: number;
  tier1Earnings: number;
  tier2Earnings: number;
  dailyFeeVolume?: number;
  monthlyFeeVolume?: number;
  ytdFeeVolume?: number;
}

interface StatsOverviewProps {
  stats: ReferralStats | undefined;
}

export function StatsOverview({ stats }: StatsOverviewProps) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
      <Card className="border-2 border-burgundy/20">
        <CardBody className="p-6">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-stable-gray">Total Referrals</p>
            <Users className="w-5 h-5 text-burgundy/60" />
          </div>
          <p className="text-3xl font-bold text-burgundy">
            {stats?.totalReferrals || 0}
          </p>
          <div className="flex gap-2 mt-3">
            <Chip color="primary" size="sm" variant="flat">
              Tier 1: {stats?.tier1Referrals || 0}
            </Chip>
            <Chip color="secondary" size="sm" variant="flat">
              Tier 2: {stats?.tier2Referrals || 0}
            </Chip>
          </div>
        </CardBody>
      </Card>

      <Card className="border-2 border-burgundy/20">
        <CardBody className="p-6">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-stable-gray">Total Volume</p>
            <TrendingUp className="w-5 h-5 text-burgundy/60" />
          </div>
          <p className="text-3xl font-bold text-burgundy">
            ${stats?.totalVolume.toLocaleString() || 0}
          </p>
          <p className="text-xs text-stable-gray mt-3">
            Tier 1: ${stats?.tier1Volume.toLocaleString() || 0} | Tier 2: $
            {stats?.tier2Volume.toLocaleString() || 0}
          </p>
        </CardBody>
      </Card>

      <Card className="border-2 border-burgundy/20">
        <CardBody className="p-6">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-stable-gray">Total Earnings</p>
            <DollarSign className="w-5 h-5 text-warm-red/60" />
          </div>
          <p className="text-3xl font-bold text-warm-red">
            ${stats?.totalEarnings.toFixed(2) || "0.00"}
          </p>
          <p className="text-xs text-stable-gray mt-3">
            Tier 1: ${stats?.tier1Earnings.toFixed(2) || "0.00"} | Tier 2: $
            {stats?.tier2Earnings.toFixed(2) || "0.00"}
          </p>
        </CardBody>
      </Card>

      <Card className="border-2 border-burgundy/20">
        <CardBody className="p-6">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-stable-gray">Your XP</p>
            <Zap className="w-5 h-5 text-burgundy/60" />
          </div>
          <p className="text-3xl font-bold text-burgundy">
            {stats?.totalVolume || 0}
          </p>
          <p className="text-xs text-stable-gray mt-3">1 USD = 1 XP</p>
        </CardBody>
      </Card>

      {/* Fee Volume Metrics */}
      {(stats?.dailyFeeVolume !== undefined ||
        stats?.monthlyFeeVolume !== undefined ||
        stats?.ytdFeeVolume !== undefined) && (
        <>
          <Card className="border-2 border-burgundy/20">
            <CardBody className="p-6">
              <div className="flex items-center justify-between mb-3">
                <p className="text-sm text-stable-gray">Fee Volume - Today</p>
                <DollarSign className="w-5 h-5 text-success/60" />
              </div>
              <p className="text-3xl font-bold text-success">
                ${stats?.dailyFeeVolume?.toLocaleString() || 0}
              </p>
              <p className="text-xs text-stable-gray mt-3">
                Generated by referrals
              </p>
            </CardBody>
          </Card>

          <Card className="border-2 border-burgundy/20">
            <CardBody className="p-6">
              <div className="flex items-center justify-between mb-3">
                <p className="text-sm text-stable-gray">
                  Fee Volume - This Month
                </p>
                <DollarSign className="w-5 h-5 text-success/60" />
              </div>
              <p className="text-3xl font-bold text-success">
                ${stats?.monthlyFeeVolume?.toLocaleString() || 0}
              </p>
              <p className="text-xs text-stable-gray mt-3">
                Generated by referrals
              </p>
            </CardBody>
          </Card>

          <Card className="border-2 border-burgundy/20">
            <CardBody className="p-6">
              <div className="flex items-center justify-between mb-3">
                <p className="text-sm text-stable-gray">Fee Volume - YTD</p>
                <DollarSign className="w-5 h-5 text-success/60" />
              </div>
              <p className="text-3xl font-bold text-success">
                ${stats?.ytdFeeVolume?.toLocaleString() || 0}
              </p>
              <p className="text-xs text-stable-gray mt-3">
                Generated by referrals
              </p>
            </CardBody>
          </Card>
        </>
      )}
    </div>
  );
}
